import "../styles/globals.css"
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "AQTAR",
  description: "Generated by AQTAR",
  openGraph: {
    title: "Product Title | AQTAR",
    description: "A detailed description of the product with relevant keywords.",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <AntdRegistry>
          <Navbar />
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
