"use client";
import React, { useState } from "react";
import { message } from "antd";
import ProductForm from "@/components/ProductForm";

export default function CreateProduct() {
  const [loading, setLoading] = useState(false);

  // Handle form submission
  const handleSubmit = async (values) => {
    setLoading(true);

    const productData = {
      id: 0, // Setting a placeholder ID (it will be auto-generated by the API)
      title: values.title,
      price: parseFloat(values.price),
      description: values.description,
      category: values.category,
      image: values.image,
    };

    try {
      // Send the POST request to the API
      const res = await fetch("https://fakestoreapi.com/products", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(productData),
      });

      if (!res.ok) {
        throw new Error("Failed to create product");
      }

      const data = await res.json();
      message.success("Product created successfully!"); // Display success message
      setLoading(false);
    } catch (error) {
      setLoading(false);
      message.error("Failed to create product"); // Display error message
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 p-6 flex items-center justify-center">
      <div className="w-full max-w-lg bg-white p-6 rounded-lg shadow-lg">
        <h1 className="text-3xl font-semibold text-center text-gray-800 mb-6">
          Create New Product
        </h1>

        <ProductForm handleSubmit={handleSubmit} loading={loading} />
      </div>
    </div>
  );
}
